use anchor_lang::prelude::*;

pub mod cross_program;
pub mod ix_introspection;

// `credmesh-shared` is a library, never deployed. This `declare_id!` exists
// only to satisfy the Anchor lint and is auto-generated by `anchor keys sync`
// from `target/deploy/credmesh_shared-keypair.json`. Real on-chain program IDs
// for the three deployable programs are exported from `program_ids` below.
declare_id!("4XbxUUL9Ck8fDh9ehRWvwUFA65kMwxYsquC941CKGoWt");

pub mod seeds {
    pub const POOL_SEED: &[u8] = b"pool";
    pub const ADVANCE_SEED: &[u8] = b"advance";
    pub const CONSUMED_SEED: &[u8] = b"consumed";
    pub const ALLOWED_SIGNER_SEED: &[u8] = b"allowed_signer";
    pub const ATTESTOR_CONFIG_SEED: &[u8] = b"attestor_config";
    pub const ISSUANCE_LEDGER_SEED: &[u8] = b"issuance_ledger";
}

pub mod program_ids {
    use anchor_lang::prelude::Pubkey;
    use anchor_lang::pubkey;

    // Devnet program IDs. Generated by `solana-keygen new` against
    // `target/deploy/credmesh_<program>-keypair.json`; kept in sync with each
    // program's own `declare_id!` and `Anchor.toml [programs.devnet]` via
    // `anchor keys sync`. Mainnet IDs will be regenerated at mainnet-launch
    // time; do not reuse devnet keypairs in mainnet (DEPLOYMENT.md §"Phase 0").
    pub const ESCROW: Pubkey = pubkey!("DLy82HRrSnSVZfQTxze8CEZwequnGyBcJNvYZX1L9yuF");
    pub const ATTESTOR_REGISTRY: Pubkey = pubkey!("ALVf6iyB6P5RFizRtxorJ3pAcc4731VziAn67sW6brvk");

    /// Squads v4 multisig program — protocol governance via timelocked vault.
    /// Verified pin: commit `64af7330413d5c85cbbccfd8c27a05d45b6e666f` /
    /// `squads-multisig-program = "=2.0.0"`. Mainnet + devnet same address.
    pub const SQUADS_V4: Pubkey = pubkey!("SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf");

    /// Memo program v2 (used for replay-nonce binding).
    pub const MEMO: Pubkey = pubkey!("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr");

    /// Native ed25519 signature-verification program.
    pub const ED25519: Pubkey = pubkey!("Ed25519SigVerify111111111111111111111111111");
}

/// Canonical layout for the ed25519-signed credit attestation that a
/// whitelisted bridge signer produces. The bridge reads EVM
/// (IdentityRegistry + ReputationRegistry + ReputationCreditOracle),
/// computes the agent's current credit_limit + outstanding, and signs
/// this 128-byte message. credmesh-escrow verifies it via instruction
/// introspection during `request_advance` — there is no on-chain
/// reputation registry on Solana; EVM is the single source of truth.
///
/// **THIS MODULE IS THE SOURCE OF TRUTH for the wire format.**
/// The TS mirror in `ts/shared/src/index.ts` (re-exported by the
/// `ts/bridge` package) MUST stay in lockstep — every offset and
/// length here has a one-line peer in the TS table, and the bridge's
/// `attestation.ts` encoder/`request_advance.rs` decoder both index by
/// these constants. A drifted offset is a silent rejection: the
/// signature verifies cryptographically but the on-chain `require!`
/// asserts trip and `request_advance` returns `Ed25519MessageMismatch`.
/// Bump `VERSION` and the TS mirror in the same commit if you change
/// any field.
///
/// Layout (128 bytes):
///   [0..32)   agent_pubkey:               agent's primary signing key
///   [32..64)  pool_pubkey:                pool PDA the attestation is for
///                                         (binds to one pool; prevents cross-pool replay)
///   [64..72)  credit_limit_atoms:  u64 LE Solana-side credit cap derived
///                                         from EVM ReputationCreditOracle
///   [72..80)  outstanding_balance: u64 LE current outstanding from EVM
///                                         (sum of all live advances across chains
///                                          tracked by the bridge)
///   [80..88)  expires_at:          i64 LE unix-ts attestation TTL
///   [88..96)  attested_at:         i64 LE bridge's attestation timestamp
///   [96..112) nonce:               16 B   request-binding nonce
///   [112..120) chain_id:           u64 LE Solana cluster id (devnet=2 / mainnet=1)
///   [120..128) version:            u64 LE message version (= 1 in v1)
pub mod ed25519_credit_message {
    pub const VERSION: u64 = 1;
    pub const TOTAL_LEN: usize = 128;

    pub const AGENT_OFFSET: usize = 0;
    pub const AGENT_LEN: usize = 32;
    pub const POOL_OFFSET: usize = 32;
    pub const POOL_LEN: usize = 32;
    pub const CREDIT_LIMIT_OFFSET: usize = 64;
    pub const CREDIT_LIMIT_LEN: usize = 8;
    pub const OUTSTANDING_OFFSET: usize = 72;
    pub const OUTSTANDING_LEN: usize = 8;
    pub const EXPIRES_AT_OFFSET: usize = 80;
    pub const EXPIRES_AT_LEN: usize = 8;
    pub const ATTESTED_AT_OFFSET: usize = 88;
    pub const ATTESTED_AT_LEN: usize = 8;
    pub const NONCE_OFFSET: usize = 96;
    pub const NONCE_LEN: usize = 16;
    pub const CHAIN_ID_OFFSET: usize = 112;
    pub const CHAIN_ID_LEN: usize = 8;
    pub const VERSION_OFFSET: usize = 120;
    pub const VERSION_LEN: usize = 8;

    /// Maximum age (in seconds) the bridge's `attested_at` may be at the
    /// time the on-chain handler runs. Caps the blast radius of a
    /// compromised bridge signer key — fraudulent attestations expire
    /// fast and need fresh signatures, giving governance time to swap
    /// the AllowedSigner via timelock.
    pub const MAX_ATTESTATION_AGE_SECONDS: i64 = 15 * 60; // 15 min

    /// Solana mainnet-beta cluster id for the chain_id field.
    pub const CHAIN_ID_MAINNET: u64 = 1;
    /// Solana devnet cluster id for the chain_id field.
    pub const CHAIN_ID_DEVNET: u64 = 2;
}

/// Whitelisted attestor kind tag stored on `AllowedSigner.kind`. v1 has
/// a single kind: a credit-attestation bridge signer that relays
/// EVM-side reputation state into Solana's request_advance. Future kinds
/// (e.g., a Pyth Lazer publisher, a multi-quorum bridge) get appended.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy, PartialEq, Eq, Debug)]
pub enum AttestorKind {
    /// Bridge signer producing ed25519_credit_message attestations.
    CreditBridge,
}

impl AttestorKind {
    pub fn as_u8(self) -> u8 {
        self as u8
    }

    pub fn from_u8(b: u8) -> Option<Self> {
        match b {
            0 => Some(Self::CreditBridge),
            _ => None,
        }
    }
}
