import { PublicKey } from "@solana/web3.js";

// Devnet program IDs. Single source of truth for the deploy + init scripts;
// must stay in sync with `Anchor.toml`, each program's `declare_id!`, and
// `crates/credmesh-shared::program_ids::*`. Generated by Track A Day 1
// (PR #16) — see DEPLOYMENT.md "Phase 0".
export const ESCROW_PROGRAM_ID = new PublicKey(
  "DLy82HRrSnSVZfQTxze8CEZwequnGyBcJNvYZX1L9yuF",
);
export const REPUTATION_PROGRAM_ID = new PublicKey(
  "JDBeDr9WFhepcz4C2JeGSsMN2KLW4C1aQdNLS2jvc79G",
);
export const RECEIVABLE_ORACLE_PROGRAM_ID = new PublicKey(
  "ALVf6iyB6P5RFizRtxorJ3pAcc4731VziAn67sW6brvk",
);

// External program IDs that the deployable programs CPI into. Mirrors
// `crates/credmesh-shared::program_ids::*` for the off-chain side.
export const MPL_AGENT_REGISTRY = new PublicKey(
  "1DREGFgysWYxLnRnKQnwrxnJQeSMk2HmGaC6whw2B2p",
);
export const MPL_CORE = new PublicKey(
  "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d",
);
export const SQUADS_V4 = new PublicKey(
  "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf",
);

// Devnet USDC (Circle). Mainnet USDC is `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`.
export const USDC_MINT_DEVNET = new PublicKey(
  "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU",
);
